### ISSUE TITLE
Missing mandatory ## AddOnVersion: <unsigned integer> tag in manifest txt file

### ISSUE THREAD

**Issue by Baertram** [bulton-fr/TESO_LibDragonWorldEvent#5]
Libraries' .txt (manifest) file should/must always contain the 
`## AddOnVersion: <unsigned integer>`
e.g. `## AddOnVersion: 211`
tag pelase so that the ingame addon manager is able to load ONLY hte newest (highest) version!
Also other addons depending on your lib are able to use `## DependsOn: LibWorldEvents=>211` then properly to make the addons NOT load if old versions are provided only, or the version is missing in total in the instaleld libraries's txt file.
This assures that addons will work properly without having the need to check for existing function names or controls ~= nil in their code.

Thanks for adding this to your txt file of this library.

Info about this can be found here;
[url]https://wiki.esoui.com/Libraries#.23.23_AddOnVersion:_.3Csigned_integer.3E[/url]

**Comment by bulton-fr** [comment]
Sorry for the delay, I do the change localy when you asked it, but for an unknown reason I blocked myself somewhere (I got lost between all addons changes to do) and not back on it since. Sorry again.  
It's added on the next release.

**Comment by Baertram** [comment]
No problem at all, it only matters if libs got different data with their different versions and old data would trouble the addons using it. Everything else not that tragically as long as the lib works with no-matter what version of it.

Thanks for adding it.
