### ISSUE TITLE
Auridon - north and south dolmens reversed

### ISSUE THREAD

**Issue by Dawnserenade** [bulton-fr/TESO_LibDragonWorldEvent#8]
Great add-on! However, in Auridon the North and South dolmens are the wrong way round (i.e. when the add-on shows the North as active, the South will be up).

I realise it's not a big deal, but it bugged me and reinstalling didn't fix it. I ended up editing the Auridon section of the Dolmen POI file from:
    [1] = 771, --Iluvamir Dolmen
    [2] = 772, --Calambar Dolmen
    [3] = 773, --Vafe Dolmen

to:
    [1] = 773, --Vafe Dolmen
    [2] = 772, --Calambar Dolmen
    [3] = 771, --Iluvamir Dolmen

**Comment by bulton-fr** [comment]
Thanks you

I will change that in next version which will add new worlds events, thanks you for the fix
I will also try to check all other maps if I have time before the chapter releases

**Comment by bulton-fr** [comment]
Fixed in the version just released (when esoui's team will accept it)
